[package]
name = "webserver"
version = "0.1.0"
edition = "2024"

[profile.dev]
panic = "unwind"

[profile.release]
panic = "unwind"

[dependencies]
ctrlc2 = "3.7.3"
uuid = { version = "1.18.1", features = ["v4"] }
